# 🔧 Operations Manager: Prometheus Configuration
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'faciliauto-monitor'
    environment: 'production'

# Alerting
alerting:
  alertmanagers:
    - static_configs:
        - targets: []
          # - alertmanager:9093

# Rule files
rule_files:
  # - "alerts/*.yml"

# Scrape configurations
scrape_configs:
  # API Metrics
  - job_name: 'faciliauto-api'
    static_configs:
      - targets: ['api:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter (system metrics)
  - job_name: 'node'
    static_configs:
      - targets: []
        # - 'node-exporter:9100'

  # Redis metrics (futuro)
  - job_name: 'redis'
    static_configs:
      - targets: []
        # - 'redis-exporter:9121'

